baseURL = 'https://phthaocse.github.io'
languageCode = 'en-us'
title = 'Thao Phan Posts'
theme = ['hugo-theme-console']
[params]
    custom_css = ['/Users/thaophan/Learning/phthaocse.github.io/assets']
[taxonomies]
  tag = "tags"
[[module.mounts]]
  source = 'images'
  target = 'static/images'
